config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  get "/register", to: "pages#register", as: "register"

  get "/login(/:user)", to: "pages#login", as: "login"

  get "/helloworld(/:user)", to: "pages#helloworld", as: "hello"

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # before_action :authenticate_user!
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    
    if current_user && current_user.id == @user.id
      @user = current_user
    else
      redirect_to root_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainingRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/helloworld.html.erb
Hello <%= @user %>

app/views/pages/login.html.erb
<%= stylesheet_link_tag "authentification", "data-turbo-track": "reload" %>
<div class="login-box">
  <h2>Login</h2>
  <form>
    <div class="user-box">
      <input type="text" name="" required="">
      <label>Username</label>
    </div>
    <div class="user-box">
      <input type="password" name="" required="">
      <label>Password</label>
    </div>
    <a href="<%= hello_path(@user) %>">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      Submit
    </a>
  </form>
</div>

app/views/pages/register.html.erb
<%= stylesheet_link_tag "authentification", "data-turbo-track": "reload" %>

<div class="login-box">
  <h2>Register</h2>
  <form>
    <div class="user-box">
      <input type="text" name="" required="">
      <label>Username</label>
    </div>
    <div class="user-box">
      <input type="password" name="" required="">
      <label>Password</label>
    </div>
    <div class="user-box">
      <input type="password" name="" required="">
      <label>Confirm Password</label>
    </div>
    <a href="<%= login_path %>">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      Submit
    </a>
  </form>
</div>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for @user do |u| %>
  <div class="form-group">
      <label>User name</label>
      <%= u.text_field :name %>
      <label>User password</label>
      <%= u.text_field :password %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Admin page users list:</h1>

<% @users.each do |user| %>
<h2> User <%= user.id %> :</h2>
<h3> <%= user.name %> </h3>
<p>

<a href="<%= user_path(user.id) %>" class="btn btn-primary">
show
</a>

</p>

<% end %>

app/views/users/show.html.erb
<div class="login-box">
    <h2>Hello <%= current_user.name %></h2>
    <form>
      <a href="#">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        Start
      </a>
      <%= link_to "Log-out", destroy_user_session_path, method: :delete %>
    </form>
  <%= stylesheet_link_tag "authentification", "data-turbo-track": "reload" %>
</div>